modLoader="kotlinforforge" #mandatory
loaderVersion="[3,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/davo899/CobblemonTrainers/issues"

[[mods]] #mandatory
modId="cobblemontrainers" #mandatory
version="${version}" #mandatory
displayName="CobblemonTrainers" #mandatory
displayURL="https://github.com/davo899/CobblemonTrainers"
#logoFile="examplemod.png" #optional
authors="selfdot"
description="Adds a trainer battle system to Cobblemon"

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

[[dependencies.cobblemontrainers]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"

[[dependencies.cobblemontrainers]]
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[40,)" #mandatory

[[dependencies.cobblemontrainers]]
modId="architectury"
mandatory=true
versionRange="[6.5.69,)"